<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 6 Introduction to Species Distribution Modeling | R Programming for Statistical Analysis</title>
  <meta name="description" content="Chapter 6 Introduction to Species Distribution Modeling | R Programming for Statistical Analysis" />
  <meta name="generator" content="bookdown 0.22 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 6 Introduction to Species Distribution Modeling | R Programming for Statistical Analysis" />
  <meta property="og:type" content="book" />
  
  
  
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 6 Introduction to Species Distribution Modeling | R Programming for Statistical Analysis" />
  
  
  

<meta name="author" content="Hammed Akande, Jeff Sauer, Abimbola Ogungbire, Tomiyosi Bola" />


<meta name="date" content="2021-07-02" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="basic-statistical-analysis.html"/>
<link rel="next" href="resources-and-references.html"/>
<script src="libs/header-attrs-2.7/header-attrs.js"></script>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<link href="libs/anchor-sections-1.0.1/anchor-sections.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.0.1/anchor-sections.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">RWorkshop</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Welcome</a></li>
<li class="chapter" data-level="2" data-path="installing-rrstudio.html"><a href="installing-rrstudio.html"><i class="fa fa-check"></i><b>2</b> Installing R/RStudio</a>
<ul>
<li class="chapter" data-level="2.1" data-path="installing-rrstudio.html"><a href="installing-rrstudio.html#to-download-r"><i class="fa fa-check"></i><b>2.1</b> To download R</a></li>
<li class="chapter" data-level="2.2" data-path="installing-rrstudio.html"><a href="installing-rrstudio.html#to-download-r-studio"><i class="fa fa-check"></i><b>2.2</b> To download R Studio</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="data-structure-and-basic-progamming-in-rstudio.html"><a href="data-structure-and-basic-progamming-in-rstudio.html"><i class="fa fa-check"></i><b>3</b> Data Structure and Basic Progamming in RStudio</a></li>
<li class="chapter" data-level="4" data-path="data-visualization.html"><a href="data-visualization.html"><i class="fa fa-check"></i><b>4</b> Data Visualization</a></li>
<li class="chapter" data-level="5" data-path="basic-statistical-analysis.html"><a href="basic-statistical-analysis.html"><i class="fa fa-check"></i><b>5</b> Basic Statistical Analysis</a>
<ul>
<li class="chapter" data-level="5.1" data-path="basic-statistical-analysis.html"><a href="basic-statistical-analysis.html#analysis-of-variance-anova"><i class="fa fa-check"></i><b>5.1</b> Analysis of Variance (ANOVA)</a>
<ul>
<li class="chapter" data-level="5.1.1" data-path="basic-statistical-analysis.html"><a href="basic-statistical-analysis.html#one-way-anova"><i class="fa fa-check"></i><b>5.1.1</b> One-Way ANOVA</a></li>
<li class="chapter" data-level="5.1.2" data-path="basic-statistical-analysis.html"><a href="basic-statistical-analysis.html#two-way-anova"><i class="fa fa-check"></i><b>5.1.2</b> TWO-Way ANOVA</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="introduction-to-species-distribution-modeling.html"><a href="introduction-to-species-distribution-modeling.html"><i class="fa fa-check"></i><b>6</b> Introduction to Species Distribution Modeling</a>
<ul>
<li class="chapter" data-level="6.0.1" data-path="introduction-to-species-distribution-modeling.html"><a href="introduction-to-species-distribution-modeling.html#downloading-the-species-data"><i class="fa fa-check"></i><b>6.0.1</b> Downloading the Species Data</a></li>
<li class="chapter" data-level="6.0.2" data-path="introduction-to-species-distribution-modeling.html"><a href="introduction-to-species-distribution-modeling.html#cleaning-the-coordinates-and-checking-for-outliers"><i class="fa fa-check"></i><b>6.0.2</b> Cleaning the coordinates and checking for outliers</a></li>
<li class="chapter" data-level="6.0.3" data-path="introduction-to-species-distribution-modeling.html"><a href="introduction-to-species-distribution-modeling.html#download-climate-data"><i class="fa fa-check"></i><b>6.0.3</b> Download Climate data</a></li>
<li class="chapter" data-level="6.0.4" data-path="introduction-to-species-distribution-modeling.html"><a href="introduction-to-species-distribution-modeling.html#generate-background-data"><i class="fa fa-check"></i><b>6.0.4</b> Generate Background data</a></li>
<li class="chapter" data-level="6.0.5" data-path="introduction-to-species-distribution-modeling.html"><a href="introduction-to-species-distribution-modeling.html#extract-the-environmental-data-for-the-mona-coordinate"><i class="fa fa-check"></i><b>6.0.5</b> Extract the environmental data for the Mona coordinate</a></li>
<li class="chapter" data-level="6.0.6" data-path="introduction-to-species-distribution-modeling.html"><a href="introduction-to-species-distribution-modeling.html#test-for-multicollinearity"><i class="fa fa-check"></i><b>6.0.6</b> Test for Multicollinearity</a></li>
<li class="chapter" data-level="6.0.7" data-path="introduction-to-species-distribution-modeling.html"><a href="introduction-to-species-distribution-modeling.html#model-selection"><i class="fa fa-check"></i><b>6.0.7</b> Model selection</a></li>
<li class="chapter" data-level="6.0.8" data-path="introduction-to-species-distribution-modeling.html"><a href="introduction-to-species-distribution-modeling.html#fitting-the-model"><i class="fa fa-check"></i><b>6.0.8</b> Fitting the model</a></li>
<li class="chapter" data-level="6.0.9" data-path="introduction-to-species-distribution-modeling.html"><a href="introduction-to-species-distribution-modeling.html#model-evaluation-and-validation"><i class="fa fa-check"></i><b>6.0.9</b> Model evaluation and validation</a></li>
<li class="chapter" data-level="6.0.10" data-path="introduction-to-species-distribution-modeling.html"><a href="introduction-to-species-distribution-modeling.html#map-prediction"><i class="fa fa-check"></i><b>6.0.10</b> Map prediction</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="resources-and-references.html"><a href="resources-and-references.html"><i class="fa fa-check"></i><b>7</b> Resources and References</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">R Programming for Statistical Analysis</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="introduction-to-species-distribution-modeling" class="section level1" number="6">
<h1><span class="header-section-number">Chapter 6</span> Introduction to Species Distribution Modeling</h1>
<p>Hammed A. Akande</p>
<p>This chapter briefly introduce you to Species Distribution Modeling (hereinafter, SDM) in R. In SDM, we relate the species occurrence data (e.g. in presence-absence format) with their environmental data (e.g. climatic data) to predict the probability of species occurring in an area or their habitat suitability. In this tutorial, I am assuming you have basic knowledge of Ecology/Wildlife/Conservation biology and statistics. I encourage you to watch my presentation video and read more online, especially if you don’t have knowledge of ecology or ecological factors that can affect species distribution.</p>
<p>Now, let’s start the modeling exercise.</p>
<p>To run this exercise, you need to install and load the required Packages. Again, I assume you know how to install and load packages, if not, refer to my Day 1 slide and video (or check the introductory section of this book). N.B- If you have installed the packages before, no need to install again, just load the library.</p>
<div class="sourceCode" id="cb61"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb61-1"><a href="introduction-to-species-distribution-modeling.html#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="co">#install.packages(&quot;dismo&quot;)</span></span>
<span id="cb61-2"><a href="introduction-to-species-distribution-modeling.html#cb61-2" aria-hidden="true" tabindex="-1"></a><span class="co">#install.packages(&quot;maptools&quot;)</span></span>
<span id="cb61-3"><a href="introduction-to-species-distribution-modeling.html#cb61-3" aria-hidden="true" tabindex="-1"></a><span class="co">#install.packages(&quot;maps&quot;)</span></span>
<span id="cb61-4"><a href="introduction-to-species-distribution-modeling.html#cb61-4" aria-hidden="true" tabindex="-1"></a><span class="co">#install.packages(&quot;mapdata&quot;)</span></span>
<span id="cb61-5"><a href="introduction-to-species-distribution-modeling.html#cb61-5" aria-hidden="true" tabindex="-1"></a><span class="co">#install.packages(&quot;dplyr&quot;)</span></span>
<span id="cb61-6"><a href="introduction-to-species-distribution-modeling.html#cb61-6" aria-hidden="true" tabindex="-1"></a><span class="co">#install.packages(&quot;CoordinateCleaner&quot;)</span></span>
<span id="cb61-7"><a href="introduction-to-species-distribution-modeling.html#cb61-7" aria-hidden="true" tabindex="-1"></a><span class="co">#install.packages(&quot;raster&quot;)</span></span>
<span id="cb61-8"><a href="introduction-to-species-distribution-modeling.html#cb61-8" aria-hidden="true" tabindex="-1"></a><span class="co">#install.packages(&quot;ggplot2&quot;)</span></span>
<span id="cb61-9"><a href="introduction-to-species-distribution-modeling.html#cb61-9" aria-hidden="true" tabindex="-1"></a><span class="co">#install.packages(&quot;scales&quot;)</span></span>
<span id="cb61-10"><a href="introduction-to-species-distribution-modeling.html#cb61-10" aria-hidden="true" tabindex="-1"></a><span class="co">#install.packages(&quot;corrplot&quot;)</span></span>
<span id="cb61-11"><a href="introduction-to-species-distribution-modeling.html#cb61-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-12"><a href="introduction-to-species-distribution-modeling.html#cb61-12" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dismo)</span></code></pre></div>
<pre><code>## Warning: package &#39;dismo&#39; was built under R version 4.0.5</code></pre>
<div class="sourceCode" id="cb63"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb63-1"><a href="introduction-to-species-distribution-modeling.html#cb63-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(maptools)</span></code></pre></div>
<pre><code>## Warning: package &#39;maptools&#39; was built under R version 4.0.5</code></pre>
<pre><code>## Checking rgeos availability: TRUE</code></pre>
<div class="sourceCode" id="cb66"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb66-1"><a href="introduction-to-species-distribution-modeling.html#cb66-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(maps)    </span></code></pre></div>
<pre><code>## Warning: package &#39;maps&#39; was built under R version 4.0.5</code></pre>
<div class="sourceCode" id="cb68"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb68-1"><a href="introduction-to-species-distribution-modeling.html#cb68-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(mapdata) </span></code></pre></div>
<pre><code>## Warning: package &#39;mapdata&#39; was built under R version 4.0.5</code></pre>
<div class="sourceCode" id="cb70"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb70-1"><a href="introduction-to-species-distribution-modeling.html#cb70-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb70-2"><a href="introduction-to-species-distribution-modeling.html#cb70-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(CoordinateCleaner)</span></code></pre></div>
<pre><code>## Warning: package &#39;CoordinateCleaner&#39; was built under R version 4.0.5</code></pre>
<div class="sourceCode" id="cb72"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb72-1"><a href="introduction-to-species-distribution-modeling.html#cb72-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(rgbif)</span>
<span id="cb72-2"><a href="introduction-to-species-distribution-modeling.html#cb72-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(corrplot)</span></code></pre></div>
<pre><code>## corrplot 0.90 loaded</code></pre>
<div class="sourceCode" id="cb74"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb74-1"><a href="introduction-to-species-distribution-modeling.html#cb74-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(raster)</span></code></pre></div>
<p>Today, we are using the GBIF website to download species data (obviously, you can load in and use your own data if you have). We shall be using the Mona Monkey as study species. Again, please read about ecology of Mona Monkey and if you don’t know of GBIF (I explained in class though) read more online about the organization.</p>
<div id="downloading-the-species-data" class="section level3" number="6.0.1">
<h3><span class="header-section-number">6.0.1</span> Downloading the Species Data</h3>
<div class="sourceCode" id="cb75"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb75-1"><a href="introduction-to-species-distribution-modeling.html#cb75-1" aria-hidden="true" tabindex="-1"></a>Mona <span class="ot">&lt;-</span> <span class="fu">occ_search</span>(<span class="at">scientificName =</span> <span class="st">&quot;Cercopithecus mona&quot;</span>, <span class="at">hasCoordinate=</span>T) </span></code></pre></div>
<p>This function “occ_search” search for the species at the GBIF website and see if there are data available. If yes, the data will be downloaded and that is only the ones with coordinate. Remember I set “hasCoordinate” to be equal to TRUE (apparently, you want to “spatially” model data with coordinates)</p>
<p>The output will be stored as “Mona” (in form of list), but we only need the data part of it, so retain the data alone.</p>
<div class="sourceCode" id="cb76"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb76-1"><a href="introduction-to-species-distribution-modeling.html#cb76-1" aria-hidden="true" tabindex="-1"></a>Mona <span class="ot">=</span> Mona<span class="sc">$</span>data </span>
<span id="cb76-2"><a href="introduction-to-species-distribution-modeling.html#cb76-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-3"><a href="introduction-to-species-distribution-modeling.html#cb76-3" aria-hidden="true" tabindex="-1"></a><span class="fu">View</span>(Mona) <span class="co">#you can view the species to see how its structured</span></span>
<span id="cb76-4"><a href="introduction-to-species-distribution-modeling.html#cb76-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-5"><a href="introduction-to-species-distribution-modeling.html#cb76-5" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(Mona)  <span class="co"># to see the first 10 observations</span></span></code></pre></div>
<pre><code>## # A tibble: 6 x 142
##   key    scientificName  decimalLatitude decimalLongitude issues  datasetKey publishingOrgKey installationKey
##   &lt;chr&gt;  &lt;chr&gt;                     &lt;dbl&gt;            &lt;dbl&gt; &lt;chr&gt;   &lt;chr&gt;      &lt;chr&gt;            &lt;chr&gt;          
## 1 25739~ Cercopithecus ~         12.1              -61.7  gass84  50c9509d-~ 28eb1a3f-1c15-4~ 997448a8-f762-~
## 2 28234~ Cercopithecus ~         12.1              -61.7  cdroun~ 50c9509d-~ 28eb1a3f-1c15-4~ 997448a8-f762-~
## 3 33113~ Cercopithecus ~          7.04               2.00 cdroun~ 70d19075-~ 071d63b5-ae0b-4~ 842b6a28-624a-~
## 4 24451~ Cercopithecus ~          0.0459             6.53 cdroun~ 50c9509d-~ 28eb1a3f-1c15-4~ 997448a8-f762-~
## 5 26112~ Cercopithecus ~          6.96               2.10 cdroun~ 50c9509d-~ 28eb1a3f-1c15-4~ 997448a8-f762-~
## 6 29885~ Cercopithecus ~         12.1              -61.7  cdroun~ 50c9509d-~ 28eb1a3f-1c15-4~ 997448a8-f762-~
## # ... with 134 more variables: publishingCountry &lt;chr&gt;, protocol &lt;chr&gt;, lastCrawled &lt;chr&gt;, lastParsed &lt;chr&gt;,
## #   crawlId &lt;int&gt;, hostingOrganizationKey &lt;chr&gt;, basisOfRecord &lt;chr&gt;, occurrenceStatus &lt;chr&gt;,
## #   taxonKey &lt;int&gt;, kingdomKey &lt;int&gt;, phylumKey &lt;int&gt;, classKey &lt;int&gt;, orderKey &lt;int&gt;, familyKey &lt;int&gt;,
## #   genusKey &lt;int&gt;, speciesKey &lt;int&gt;, acceptedTaxonKey &lt;int&gt;, acceptedScientificName &lt;chr&gt;, kingdom &lt;chr&gt;,
## #   phylum &lt;chr&gt;, order &lt;chr&gt;, family &lt;chr&gt;, genus &lt;chr&gt;, species &lt;chr&gt;, genericName &lt;chr&gt;,
## #   specificEpithet &lt;chr&gt;, taxonRank &lt;chr&gt;, taxonomicStatus &lt;chr&gt;, iucnRedListCategory &lt;chr&gt;,
## #   dateIdentified &lt;chr&gt;, stateProvince &lt;chr&gt;, year &lt;int&gt;, month &lt;int&gt;, day &lt;int&gt;, eventDate &lt;chr&gt;,
## #   modified &lt;chr&gt;, lastInterpreted &lt;chr&gt;, references &lt;chr&gt;, license &lt;chr&gt;, identifiers &lt;chr&gt;, facts &lt;chr&gt;,
## #   relations &lt;chr&gt;, isInCluster &lt;lgl&gt;, geodeticDatum &lt;chr&gt;, class &lt;chr&gt;, countryCode &lt;chr&gt;,
## #   recordedByIDs &lt;chr&gt;, identifiedByIDs &lt;chr&gt;, country &lt;chr&gt;, rightsHolder &lt;chr&gt;, identifier &lt;chr&gt;,
## #   http...unknown.org.nick &lt;chr&gt;, verbatimEventDate &lt;chr&gt;, datasetName &lt;chr&gt;, verbatimLocality &lt;chr&gt;,
## #   gbifID &lt;chr&gt;, collectionCode &lt;chr&gt;, occurrenceID &lt;chr&gt;, taxonID &lt;chr&gt;, catalogNumber &lt;chr&gt;,
## #   recordedBy &lt;chr&gt;, http...unknown.org.occurrenceDetails &lt;chr&gt;, institutionCode &lt;chr&gt;, rights &lt;chr&gt;,
## #   eventTime &lt;chr&gt;, identifiedBy &lt;chr&gt;, identificationID &lt;chr&gt;, name &lt;chr&gt;,
## #   coordinateUncertaintyInMeters &lt;dbl&gt;, projectId &lt;chr&gt;, continent &lt;chr&gt;, habitat &lt;chr&gt;, locality &lt;chr&gt;,
## #   samplingProtocol &lt;chr&gt;, occurrenceRemarks &lt;chr&gt;, individualCount &lt;int&gt;, lifeStage &lt;chr&gt;,
## #   vernacularName &lt;chr&gt;, higherClassification &lt;chr&gt;, collectionID &lt;chr&gt;, programmeAcronym &lt;chr&gt;,
## #   organismQuantityType &lt;chr&gt;, institutionID &lt;chr&gt;, county &lt;chr&gt;,
## #   http...rs.tdwg.org.dwc.terms.organismQuantityType &lt;chr&gt;, collectionKey &lt;chr&gt;, institutionKey &lt;chr&gt;,
## #   identifiedByIDs.type &lt;chr&gt;, identifiedByIDs.value &lt;chr&gt;, sex &lt;chr&gt;,
## #   X.99d66b6c.9087.452f.a9d4.f15f2c2d0e7e. &lt;chr&gt;, establishmentMeans &lt;chr&gt;, higherGeography &lt;chr&gt;,
## #   nomenclaturalCode &lt;chr&gt;, endDayOfYear &lt;chr&gt;, georeferenceVerificationStatus &lt;chr&gt;, language &lt;chr&gt;,
## #   type &lt;chr&gt;, startDayOfYear &lt;chr&gt;, accessRights &lt;chr&gt;, ...</code></pre>
<p>How about we define the extent of our species to know the min and max longitude and latitude of the species? That should make sense I guess. So, set the geographic extent.</p>
<div class="sourceCode" id="cb78"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb78-1"><a href="introduction-to-species-distribution-modeling.html#cb78-1" aria-hidden="true" tabindex="-1"></a>max.lat <span class="ot">&lt;-</span> <span class="fu">ceiling</span>(<span class="fu">max</span>(Mona<span class="sc">$</span>decimalLatitude))</span>
<span id="cb78-2"><a href="introduction-to-species-distribution-modeling.html#cb78-2" aria-hidden="true" tabindex="-1"></a>min.lat <span class="ot">&lt;-</span> <span class="fu">floor</span>(<span class="fu">min</span>(Mona<span class="sc">$</span>decimalLatitude))</span>
<span id="cb78-3"><a href="introduction-to-species-distribution-modeling.html#cb78-3" aria-hidden="true" tabindex="-1"></a>max.lon <span class="ot">&lt;-</span> <span class="fu">ceiling</span>(<span class="fu">max</span>(Mona<span class="sc">$</span>decimalLongitude))</span>
<span id="cb78-4"><a href="introduction-to-species-distribution-modeling.html#cb78-4" aria-hidden="true" tabindex="-1"></a>min.lon <span class="ot">&lt;-</span> <span class="fu">floor</span>(<span class="fu">min</span>(Mona<span class="sc">$</span>decimalLongitude))</span>
<span id="cb78-5"><a href="introduction-to-species-distribution-modeling.html#cb78-5" aria-hidden="true" tabindex="-1"></a>geographic.extent <span class="ot">&lt;-</span> <span class="fu">extent</span>(<span class="at">x =</span> <span class="fu">c</span>(min.lon, max.lon, min.lat, max.lat))</span>
<span id="cb78-6"><a href="introduction-to-species-distribution-modeling.html#cb78-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb78-7"><a href="introduction-to-species-distribution-modeling.html#cb78-7" aria-hidden="true" tabindex="-1"></a>geographic.extent</span></code></pre></div>
<pre><code>## class      : Extent 
## xmin       : -62 
## xmax       : 30 
## ymin       : -5 
## ymax       : 49</code></pre>
<p>Now, let’s just check it on map to even know where our species are located in space.</p>
<div class="sourceCode" id="cb80"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb80-1"><a href="introduction-to-species-distribution-modeling.html#cb80-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(wrld_simpl)</span>
<span id="cb80-2"><a href="introduction-to-species-distribution-modeling.html#cb80-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb80-3"><a href="introduction-to-species-distribution-modeling.html#cb80-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Base map</span></span>
<span id="cb80-4"><a href="introduction-to-species-distribution-modeling.html#cb80-4" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(wrld_simpl, </span>
<span id="cb80-5"><a href="introduction-to-species-distribution-modeling.html#cb80-5" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlim =</span> <span class="fu">c</span>(min.lon, max.lon),</span>
<span id="cb80-6"><a href="introduction-to-species-distribution-modeling.html#cb80-6" aria-hidden="true" tabindex="-1"></a>     <span class="at">ylim =</span> <span class="fu">c</span>(min.lat, max.lat),</span>
<span id="cb80-7"><a href="introduction-to-species-distribution-modeling.html#cb80-7" aria-hidden="true" tabindex="-1"></a>     <span class="at">axes =</span> <span class="cn">TRUE</span>, </span>
<span id="cb80-8"><a href="introduction-to-species-distribution-modeling.html#cb80-8" aria-hidden="true" tabindex="-1"></a>     <span class="at">col =</span> <span class="st">&quot;grey95&quot;</span>)</span>
<span id="cb80-9"><a href="introduction-to-species-distribution-modeling.html#cb80-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb80-10"><a href="introduction-to-species-distribution-modeling.html#cb80-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Individual obs points</span></span>
<span id="cb80-11"><a href="introduction-to-species-distribution-modeling.html#cb80-11" aria-hidden="true" tabindex="-1"></a><span class="fu">points</span>(<span class="at">x =</span> Mona<span class="sc">$</span>decimalLongitude, </span>
<span id="cb80-12"><a href="introduction-to-species-distribution-modeling.html#cb80-12" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> Mona<span class="sc">$</span>decimalLatitude, </span>
<span id="cb80-13"><a href="introduction-to-species-distribution-modeling.html#cb80-13" aria-hidden="true" tabindex="-1"></a>       <span class="at">col =</span> <span class="st">&quot;red&quot;</span>, </span>
<span id="cb80-14"><a href="introduction-to-species-distribution-modeling.html#cb80-14" aria-hidden="true" tabindex="-1"></a>       <span class="at">pch =</span> <span class="dv">20</span>, </span>
<span id="cb80-15"><a href="introduction-to-species-distribution-modeling.html#cb80-15" aria-hidden="true" tabindex="-1"></a>       <span class="at">cex =</span> <span class="fl">0.75</span>)</span>
<span id="cb80-16"><a href="introduction-to-species-distribution-modeling.html#cb80-16" aria-hidden="true" tabindex="-1"></a><span class="fu">box</span>()</span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-21-1.png" width="672" /></p>
<p>Voila! That’s better. Looking at something in picture/plot/map make more sense I guess.</p>
</div>
<div id="cleaning-the-coordinates-and-checking-for-outliers" class="section level3" number="6.0.2">
<h3><span class="header-section-number">6.0.2</span> Cleaning the coordinates and checking for outliers</h3>
<p>At least now you know where they are located, but are you really sure all points are accurate? Do they all look correct? Do you think there might be errors in species collection or even when recording them? Or might be biased in any way? So, the best way to be sure is to do some “Data quality” checking.</p>
<p>Let’s use a package called CoordinateCleaner for this. I am testing for duplicates, centroids outliers and to check how far away from biodiversity institutions. use the code ?CoordinateCleaner to know more about what you can test for.</p>
<div class="sourceCode" id="cb81"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb81-1"><a href="introduction-to-species-distribution-modeling.html#cb81-1" aria-hidden="true" tabindex="-1"></a>clean_Mona <span class="ot">&lt;-</span> <span class="fu">clean_coordinates</span>(Mona, <span class="at">lon=</span><span class="st">&quot;decimalLongitude&quot;</span>,<span class="at">lat=</span><span class="st">&quot;decimalLatitude&quot;</span>, </span>
<span id="cb81-2"><a href="introduction-to-species-distribution-modeling.html#cb81-2" aria-hidden="true" tabindex="-1"></a>                                       <span class="at">tests=</span><span class="fu">c</span>(<span class="st">&quot;centroids&quot;</span>, <span class="st">&quot;outliers&quot;</span>, <span class="st">&quot;duplicates&quot;</span>, <span class="st">&quot;institutions&quot;</span>),<span class="at">inst_rad =</span> <span class="dv">10000</span>)</span></code></pre></div>
<pre><code>## Testing coordinate validity</code></pre>
<pre><code>## Flagged 0 records.</code></pre>
<pre><code>## Testing country centroids</code></pre>
<pre><code>## Flagged 1 records.</code></pre>
<pre><code>## Testing geographic outliers</code></pre>
<pre><code>## Flagged 23 records.</code></pre>
<pre><code>## Testing biodiversity institutions</code></pre>
<pre><code>## Flagged 14 records.</code></pre>
<pre><code>## Testing duplicates</code></pre>
<pre><code>## Flagged 185 records.</code></pre>
<pre><code>## Flagged 206 of 373 records, EQ = 0.55.</code></pre>
<p>Wow, 206 of 373 flagged. See why you need to clean data now? Else, your model(s) will be biased.</p>
<p>Let’s subset the data to only cleaned version now.</p>
<div class="sourceCode" id="cb93"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb93-1"><a href="introduction-to-species-distribution-modeling.html#cb93-1" aria-hidden="true" tabindex="-1"></a>clean_Mona <span class="ot">=</span> clean_Mona[clean_Mona<span class="sc">$</span>.summary,]</span></code></pre></div>
<p>If you check the “clean_Mona”, you will see there are many variables. We really don’t need all of them for analysis, so why not just retain the variables will only need</p>
<div class="sourceCode" id="cb94"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb94-1"><a href="introduction-to-species-distribution-modeling.html#cb94-1" aria-hidden="true" tabindex="-1"></a>clean_Mona <span class="ot">=</span> clean_Mona[, <span class="fu">c</span>(<span class="st">&quot;species&quot;</span>, <span class="st">&quot;decimalLatitude&quot;</span>, <span class="st">&quot;decimalLongitude&quot;</span>)] </span>
<span id="cb94-2"><a href="introduction-to-species-distribution-modeling.html#cb94-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb94-3"><a href="introduction-to-species-distribution-modeling.html#cb94-3" aria-hidden="true" tabindex="-1"></a><span class="co"># or through the dplyr package. Of course, you will get the same result</span></span>
<span id="cb94-4"><a href="introduction-to-species-distribution-modeling.html#cb94-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb94-5"><a href="introduction-to-species-distribution-modeling.html#cb94-5" aria-hidden="true" tabindex="-1"></a>clean_Mona <span class="ot">&lt;-</span>clean_Mona <span class="sc">%&gt;%</span> </span>
<span id="cb94-6"><a href="introduction-to-species-distribution-modeling.html#cb94-6" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">select</span>(species, decimalLatitude, decimalLongitude)</span></code></pre></div>
<p>Remember if the species list contains the name of the species. We need it in presence/absence format (I explained in class). So, let’s turn the species name to 1 (for presence)</p>
<div class="sourceCode" id="cb95"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb95-1"><a href="introduction-to-species-distribution-modeling.html#cb95-1" aria-hidden="true" tabindex="-1"></a>Mona_P <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(clean_Mona, <span class="at">occ=</span><span class="dv">1</span>)</span>
<span id="cb95-2"><a href="introduction-to-species-distribution-modeling.html#cb95-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb95-3"><a href="introduction-to-species-distribution-modeling.html#cb95-3" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(Mona_P)</span></code></pre></div>
<pre><code>##              species decimalLatitude decimalLongitude occ
## 3 Cercopithecus mona        7.038812         1.999688   1
## 4 Cercopithecus mona        0.045902         6.528708   1
## 5 Cercopithecus mona        6.956431         2.097323   1
## 7 Cercopithecus mona        7.721062        -1.701965   1
## 8 Cercopithecus mona        6.438185         3.534619   1
## 9 Cercopithecus mona        6.591946         3.948594   1</code></pre>
<div class="sourceCode" id="cb97"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb97-1"><a href="introduction-to-species-distribution-modeling.html#cb97-1" aria-hidden="true" tabindex="-1"></a><span class="co"># You see a new column is now added, called &quot;occ&quot; (as in short form of occurence)</span></span>
<span id="cb97-2"><a href="introduction-to-species-distribution-modeling.html#cb97-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb97-3"><a href="introduction-to-species-distribution-modeling.html#cb97-3" aria-hidden="true" tabindex="-1"></a><span class="co"># If you wish to export this clean data (e.g. to csv), for further analysis, you can do that now. </span></span>
<span id="cb97-4"><a href="introduction-to-species-distribution-modeling.html#cb97-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb97-5"><a href="introduction-to-species-distribution-modeling.html#cb97-5" aria-hidden="true" tabindex="-1"></a><span class="co">#write.csv(clean_Mona, &quot;Mona_cleaned.csv&quot;, row.names = FALSE)</span></span></code></pre></div>
<p>Don’t forget that SDM (as in the case of correlative), we want to relate the species with their environment to understand factors affecting them.</p>
<p>So, let’s the Get the climate data.</p>
</div>
<div id="download-climate-data" class="section level3" number="6.0.3">
<h3><span class="header-section-number">6.0.3</span> Download Climate data</h3>
<p>You can get climate data from worldclim, chelsa and paleoclim, among others.</p>
<div class="sourceCode" id="cb98"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb98-1"><a href="introduction-to-species-distribution-modeling.html#cb98-1" aria-hidden="true" tabindex="-1"></a><span class="co"># You may want to set directory to store it </span></span>
<span id="cb98-2"><a href="introduction-to-species-distribution-modeling.html#cb98-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb98-3"><a href="introduction-to-species-distribution-modeling.html#cb98-3" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span>(<span class="sc">!</span><span class="fu">dir.exists</span>(<span class="st">&quot;bioclim_data&quot;</span>)){</span>
<span id="cb98-4"><a href="introduction-to-species-distribution-modeling.html#cb98-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">dir.create</span>(<span class="st">&quot;bioclim_data&quot;</span>, <span class="at">recursive =</span> <span class="cn">TRUE</span>)</span>
<span id="cb98-5"><a href="introduction-to-species-distribution-modeling.html#cb98-5" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb98-6"><a href="introduction-to-species-distribution-modeling.html#cb98-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb98-7"><a href="introduction-to-species-distribution-modeling.html#cb98-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb98-8"><a href="introduction-to-species-distribution-modeling.html#cb98-8" aria-hidden="true" tabindex="-1"></a> clim_data <span class="ot">&lt;-</span> <span class="fu">getData</span>(<span class="at">name =</span> <span class="st">&quot;worldclim&quot;</span>,</span>
<span id="cb98-9"><a href="introduction-to-species-distribution-modeling.html#cb98-9" aria-hidden="true" tabindex="-1"></a>                     <span class="at">var =</span> <span class="st">&quot;bio&quot;</span>,</span>
<span id="cb98-10"><a href="introduction-to-species-distribution-modeling.html#cb98-10" aria-hidden="true" tabindex="-1"></a>                        <span class="at">res =</span> <span class="dv">5</span>,</span>
<span id="cb98-11"><a href="introduction-to-species-distribution-modeling.html#cb98-11" aria-hidden="true" tabindex="-1"></a>                        <span class="at">path =</span> <span class="st">&quot;bioclim_data&quot;</span>,</span>
<span id="cb98-12"><a href="introduction-to-species-distribution-modeling.html#cb98-12" aria-hidden="true" tabindex="-1"></a>                        <span class="at">download =</span> T)</span></code></pre></div>
<p>In SDM, to every presence, there should be absence. As you may know, absence data are often not available and so we can generate background (or pseudo-absence) data.</p>
</div>
<div id="generate-background-data" class="section level3" number="6.0.4">
<h3><span class="header-section-number">6.0.4</span> Generate Background data</h3>
<p>Let’s generate Background data using the climate data we just downloaded as the sampling resolution</p>
<div class="sourceCode" id="cb99"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb99-1"><a href="introduction-to-species-distribution-modeling.html#cb99-1" aria-hidden="true" tabindex="-1"></a>bil.files <span class="ot">&lt;-</span> <span class="fu">list.files</span>(<span class="at">path =</span> <span class="st">&quot;bioclim_data/wc5&quot;</span>, </span>
<span id="cb99-2"><a href="introduction-to-species-distribution-modeling.html#cb99-2" aria-hidden="true" tabindex="-1"></a>                        <span class="at">pattern =</span> <span class="st">&quot;*.bil$&quot;</span>, </span>
<span id="cb99-3"><a href="introduction-to-species-distribution-modeling.html#cb99-3" aria-hidden="true" tabindex="-1"></a>                        <span class="at">full.names =</span> <span class="cn">TRUE</span>)</span>
<span id="cb99-4"><a href="introduction-to-species-distribution-modeling.html#cb99-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb99-5"><a href="introduction-to-species-distribution-modeling.html#cb99-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Let&#39;s just use one of the .bil files to mask the background data, we don&#39;t really need all</span></span>
<span id="cb99-6"><a href="introduction-to-species-distribution-modeling.html#cb99-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb99-7"><a href="introduction-to-species-distribution-modeling.html#cb99-7" aria-hidden="true" tabindex="-1"></a>mask <span class="ot">&lt;-</span> <span class="fu">raster</span>(bil.files[<span class="dv">1</span>])</span>
<span id="cb99-8"><a href="introduction-to-species-distribution-modeling.html#cb99-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb99-9"><a href="introduction-to-species-distribution-modeling.html#cb99-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Use the randomPoints function to randomly sample points. Now, we shall sample the same number of points as our observed points (and extend it by 1.25). By sampling same number of occurence point and giving a bit room for extension, we are conservative enough and reduce bias.</span></span>
<span id="cb99-10"><a href="introduction-to-species-distribution-modeling.html#cb99-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb99-11"><a href="introduction-to-species-distribution-modeling.html#cb99-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb99-12"><a href="introduction-to-species-distribution-modeling.html#cb99-12" aria-hidden="true" tabindex="-1"></a>background <span class="ot">&lt;-</span> <span class="fu">randomPoints</span>(<span class="at">mask =</span> mask, <span class="at">n =</span> <span class="fu">nrow</span>(Mona_P), <span class="at">ext =</span> geographic.extent, <span class="at">extf =</span> <span class="fl">1.25</span>)</span></code></pre></div>
<p>How about we Plot them on map (presence and pseudo-absence)</p>
<div class="sourceCode" id="cb100"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb100-1"><a href="introduction-to-species-distribution-modeling.html#cb100-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(wrld_simpl, </span>
<span id="cb100-2"><a href="introduction-to-species-distribution-modeling.html#cb100-2" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlim =</span> <span class="fu">c</span>(min.lon, max.lon),</span>
<span id="cb100-3"><a href="introduction-to-species-distribution-modeling.html#cb100-3" aria-hidden="true" tabindex="-1"></a>     <span class="at">ylim =</span> <span class="fu">c</span>(min.lat, max.lat),</span>
<span id="cb100-4"><a href="introduction-to-species-distribution-modeling.html#cb100-4" aria-hidden="true" tabindex="-1"></a>     <span class="at">axes =</span> <span class="cn">TRUE</span>, </span>
<span id="cb100-5"><a href="introduction-to-species-distribution-modeling.html#cb100-5" aria-hidden="true" tabindex="-1"></a>     <span class="at">col =</span> <span class="st">&quot;grey35&quot;</span>,</span>
<span id="cb100-6"><a href="introduction-to-species-distribution-modeling.html#cb100-6" aria-hidden="true" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">&quot;Presence and pseudo-absence points&quot;</span>)</span>
<span id="cb100-7"><a href="introduction-to-species-distribution-modeling.html#cb100-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb100-8"><a href="introduction-to-species-distribution-modeling.html#cb100-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Add the background points</span></span>
<span id="cb100-9"><a href="introduction-to-species-distribution-modeling.html#cb100-9" aria-hidden="true" tabindex="-1"></a><span class="fu">points</span>(background, <span class="at">col =</span> <span class="st">&quot;green&quot;</span>, <span class="at">pch =</span> <span class="dv">1</span>, <span class="at">cex =</span> <span class="fl">0.75</span>)</span>
<span id="cb100-10"><a href="introduction-to-species-distribution-modeling.html#cb100-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb100-11"><a href="introduction-to-species-distribution-modeling.html#cb100-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Add the observations</span></span>
<span id="cb100-12"><a href="introduction-to-species-distribution-modeling.html#cb100-12" aria-hidden="true" tabindex="-1"></a><span class="fu">points</span>(<span class="at">x =</span> Mona_P<span class="sc">$</span>decimalLongitude, </span>
<span id="cb100-13"><a href="introduction-to-species-distribution-modeling.html#cb100-13" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> Mona_P<span class="sc">$</span>decimalLatitude, </span>
<span id="cb100-14"><a href="introduction-to-species-distribution-modeling.html#cb100-14" aria-hidden="true" tabindex="-1"></a>       <span class="at">col =</span> <span class="st">&quot;red&quot;</span>, </span>
<span id="cb100-15"><a href="introduction-to-species-distribution-modeling.html#cb100-15" aria-hidden="true" tabindex="-1"></a>       <span class="at">pch =</span> <span class="dv">20</span>, </span>
<span id="cb100-16"><a href="introduction-to-species-distribution-modeling.html#cb100-16" aria-hidden="true" tabindex="-1"></a>       <span class="at">cex =</span> <span class="fl">0.75</span>)</span>
<span id="cb100-17"><a href="introduction-to-species-distribution-modeling.html#cb100-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb100-18"><a href="introduction-to-species-distribution-modeling.html#cb100-18" aria-hidden="true" tabindex="-1"></a><span class="fu">box</span>()</span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-28-1.png" width="672" /></p>
<p>Now, what we can do is to join them together.</p>
<div class="sourceCode" id="cb101"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb101-1"><a href="introduction-to-species-distribution-modeling.html#cb101-1" aria-hidden="true" tabindex="-1"></a>Mona_P <span class="ot">=</span> Mona_P[, <span class="fu">c</span>(<span class="st">&quot;decimalLongitude&quot;</span>, <span class="st">&quot;decimalLatitude&quot;</span>, <span class="st">&quot;occ&quot;</span>)] <span class="co"># since we don&#39;t need the column &quot;species&quot; again, we can remove it. </span></span>
<span id="cb101-2"><a href="introduction-to-species-distribution-modeling.html#cb101-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb101-3"><a href="introduction-to-species-distribution-modeling.html#cb101-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb101-4"><a href="introduction-to-species-distribution-modeling.html#cb101-4" aria-hidden="true" tabindex="-1"></a>background_dat <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(background) <span class="co"># put it in dataframe</span></span>
<span id="cb101-5"><a href="introduction-to-species-distribution-modeling.html#cb101-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(background_dat)</span></code></pre></div>
<pre><code>##        x                 y          
##  Min.   :-72.792   Min.   :-11.542  
##  1st Qu.: -2.708   1st Qu.:  1.458  
##  Median : 12.958   Median : 14.792  
##  Mean   :  4.572   Mean   : 17.108  
##  3rd Qu.: 29.167   3rd Qu.: 29.792  
##  Max.   : 40.625   Max.   : 55.042</code></pre>
<div class="sourceCode" id="cb103"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb103-1"><a href="introduction-to-species-distribution-modeling.html#cb103-1" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(background_dat) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&#39;decimalLongitude&#39;</span>,<span class="st">&#39;decimalLatitude&#39;</span>) <span class="co"># set the name of background_dat instead form &quot;x&quot; and &quot;y&quot; to Longitude and Latitude</span></span>
<span id="cb103-2"><a href="introduction-to-species-distribution-modeling.html#cb103-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb103-3"><a href="introduction-to-species-distribution-modeling.html#cb103-3" aria-hidden="true" tabindex="-1"></a>background_dat<span class="sc">$</span>occ <span class="ot">&lt;-</span> <span class="dv">0</span>  <span class="co"># set absence data to 0 (remember we set presence to 1)</span></span>
<span id="cb103-4"><a href="introduction-to-species-distribution-modeling.html#cb103-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(background_dat)</span></code></pre></div>
<pre><code>##  decimalLongitude  decimalLatitude        occ   
##  Min.   :-72.792   Min.   :-11.542   Min.   :0  
##  1st Qu.: -2.708   1st Qu.:  1.458   1st Qu.:0  
##  Median : 12.958   Median : 14.792   Median :0  
##  Mean   :  4.572   Mean   : 17.108   Mean   :0  
##  3rd Qu.: 29.167   3rd Qu.: 29.792   3rd Qu.:0  
##  Max.   : 40.625   Max.   : 55.042   Max.   :0</code></pre>
<div class="sourceCode" id="cb105"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb105-1"><a href="introduction-to-species-distribution-modeling.html#cb105-1" aria-hidden="true" tabindex="-1"></a>Mona_PA <span class="ot">&lt;-</span> <span class="fu">rbind</span>(Mona_P, background_dat) <span class="co"># use the &quot;rbind&quot; function to row bind them. </span></span>
<span id="cb105-2"><a href="introduction-to-species-distribution-modeling.html#cb105-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(Mona_PA)</span></code></pre></div>
<pre><code>##  decimalLongitude  decimalLatitude        occ     
##  Min.   :-72.792   Min.   :-11.542   Min.   :0.0  
##  1st Qu.:  1.738   1st Qu.:  5.896   1st Qu.:0.0  
##  Median :  2.686   Median :  6.909   Median :0.5  
##  Mean   :  3.857   Mean   : 11.830   Mean   :0.5  
##  3rd Qu.: 14.417   3rd Qu.: 14.792   3rd Qu.:1.0  
##  Max.   : 40.625   Max.   : 55.042   Max.   :1.0</code></pre>
<div class="sourceCode" id="cb107"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb107-1"><a href="introduction-to-species-distribution-modeling.html#cb107-1" aria-hidden="true" tabindex="-1"></a>Mona_PA <span class="ot">=</span> <span class="fu">data.frame</span>(Mona_PA)</span>
<span id="cb107-2"><a href="introduction-to-species-distribution-modeling.html#cb107-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb107-3"><a href="introduction-to-species-distribution-modeling.html#cb107-3" aria-hidden="true" tabindex="-1"></a>dplyr<span class="sc">::</span><span class="fu">sample_n</span>(Mona_PA, <span class="dv">10</span>) <span class="co"># randomly check 10 observations</span></span></code></pre></div>
<pre><code>##      decimalLongitude decimalLatitude occ
## 92           2.512721        6.904417   1
## 240          9.400000        5.833300   1
## 321        -65.875000       -7.541667   0
## 110          2.427500        8.490000   1
## 541        -68.291667        8.291667   0
## 179        -13.125000       11.625000   0
## 259         18.000000        9.000000   1
## 125          2.166667        6.916667   1
## 751         14.041667       28.625000   0
## 1410        38.375000       14.625000   0</code></pre>
</div>
<div id="extract-the-environmental-data-for-the-mona-coordinate" class="section level3" number="6.0.5">
<h3><span class="header-section-number">6.0.5</span> Extract the environmental data for the Mona coordinate</h3>
<div class="sourceCode" id="cb109"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb109-1"><a href="introduction-to-species-distribution-modeling.html#cb109-1" aria-hidden="true" tabindex="-1"></a>Mona_PA <span class="ot">=</span> <span class="fu">cbind</span>(Mona_PA, raster<span class="sc">::</span><span class="fu">extract</span>(<span class="at">x =</span> clim_data, <span class="at">y =</span> <span class="fu">data.frame</span>(Mona_PA[,<span class="fu">c</span>(<span class="st">&#39;decimalLongitude&#39;</span>,<span class="st">&#39;decimalLatitude&#39;</span>)]), <span class="at">cellnumbers=</span>T ))</span>
<span id="cb109-2"><a href="introduction-to-species-distribution-modeling.html#cb109-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb109-3"><a href="introduction-to-species-distribution-modeling.html#cb109-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb109-4"><a href="introduction-to-species-distribution-modeling.html#cb109-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Check if there are duplicated cells </span></span>
<span id="cb109-5"><a href="introduction-to-species-distribution-modeling.html#cb109-5" aria-hidden="true" tabindex="-1"></a><span class="fu">duplicated</span>(Mona_PA<span class="sc">$</span>cells)</span></code></pre></div>
<pre><code>##   [1] FALSE FALSE FALSE FALSE FALSE FALSE  TRUE FALSE FALSE FALSE FALSE FALSE FALSE  TRUE  TRUE FALSE  TRUE
##  [18] FALSE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE  TRUE
##  [35] FALSE FALSE FALSE  TRUE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE  TRUE FALSE FALSE  TRUE  TRUE
##  [52]  TRUE FALSE  TRUE  TRUE  TRUE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE  TRUE  TRUE FALSE  TRUE
##  [69]  TRUE FALSE FALSE  TRUE FALSE FALSE FALSE  TRUE FALSE FALSE FALSE FALSE FALSE FALSE  TRUE  TRUE FALSE
##  [86]  TRUE FALSE FALSE FALSE  TRUE FALSE FALSE FALSE FALSE FALSE  TRUE  TRUE  TRUE FALSE  TRUE  TRUE  TRUE
## [103]  TRUE  TRUE FALSE  TRUE  TRUE FALSE  TRUE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
## [120] FALSE FALSE FALSE FALSE FALSE FALSE  TRUE FALSE FALSE  TRUE FALSE FALSE FALSE FALSE  TRUE FALSE FALSE
## [137] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE  TRUE FALSE FALSE FALSE FALSE FALSE FALSE
## [154] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
## [171] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
## [188] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
## [205] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
## [222] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
## [239] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
## [256] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
## [273] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
## [290] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
## [307] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
## [324] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE</code></pre>
<p>You can see some duplicated cells, right? So, let’s retains non-duplicated cells (obviously, you don’t want to have duplicated cells in analysis)</p>
<p>Retain non-duplicated cells</p>
<div class="sourceCode" id="cb111"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb111-1"><a href="introduction-to-species-distribution-modeling.html#cb111-1" aria-hidden="true" tabindex="-1"></a>Mona_PA <span class="ot">&lt;-</span> Mona_PA[<span class="sc">!</span><span class="fu">duplicated</span>(Mona_PA<span class="sc">$</span>cells),]</span>
<span id="cb111-2"><a href="introduction-to-species-distribution-modeling.html#cb111-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb111-3"><a href="introduction-to-species-distribution-modeling.html#cb111-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Now check again if there are duplicated cells (I am certain it will all be FALSE now)</span></span>
<span id="cb111-4"><a href="introduction-to-species-distribution-modeling.html#cb111-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb111-5"><a href="introduction-to-species-distribution-modeling.html#cb111-5" aria-hidden="true" tabindex="-1"></a><span class="fu">duplicated</span>(Mona_PA<span class="sc">$</span>cells)</span></code></pre></div>
<pre><code>##   [1] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
##  [18] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
##  [35] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
##  [52] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
##  [69] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
##  [86] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
## [103] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
## [120] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
## [137] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
## [154] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
## [171] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
## [188] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
## [205] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
## [222] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
## [239] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
## [256] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
## [273] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
## [290] FALSE</code></pre>
<p>Check for missing values (NA)</p>
<div class="sourceCode" id="cb113"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb113-1"><a href="introduction-to-species-distribution-modeling.html#cb113-1" aria-hidden="true" tabindex="-1"></a><span class="fu">any</span>(<span class="fu">is.na</span>(Mona_PA)) <span class="co"># Check for NA</span></span></code></pre></div>
<pre><code>## [1] TRUE</code></pre>
<p>Clear enough right? We have missing values, so let’s remove them</p>
<p>Remove NA</p>
<div class="sourceCode" id="cb115"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb115-1"><a href="introduction-to-species-distribution-modeling.html#cb115-1" aria-hidden="true" tabindex="-1"></a>Mona_PA <span class="ot">=</span> <span class="fu">na.omit</span>(Mona_PA) <span class="co"># remove NA</span></span>
<span id="cb115-2"><a href="introduction-to-species-distribution-modeling.html#cb115-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb115-3"><a href="introduction-to-species-distribution-modeling.html#cb115-3" aria-hidden="true" tabindex="-1"></a><span class="co"># check again. This time, it should be FALSE</span></span>
<span id="cb115-4"><a href="introduction-to-species-distribution-modeling.html#cb115-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb115-5"><a href="introduction-to-species-distribution-modeling.html#cb115-5" aria-hidden="true" tabindex="-1"></a><span class="fu">any</span>(<span class="fu">is.na</span>(Mona_PA))</span></code></pre></div>
<pre><code>## [1] FALSE</code></pre>
<p>That’s it. We can start the process of model fitting</p>
<p>Before we even start, its a good idea to test for multicollinearity (to be sure we don’t have multicollinear variables). I explained why this is not good in class- watch the video or read more online.</p>
</div>
<div id="test-for-multicollinearity" class="section level3" number="6.0.6">
<h3><span class="header-section-number">6.0.6</span> Test for Multicollinearity</h3>
<p>Build a correlation matrix</p>
<div class="sourceCode" id="cb117"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb117-1"><a href="introduction-to-species-distribution-modeling.html#cb117-1" aria-hidden="true" tabindex="-1"></a>cor_mat <span class="ot">&lt;-</span> <span class="fu">cor</span>(Mona_PA[,<span class="sc">-</span><span class="fu">c</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">6</span>)], <span class="at">method=</span><span class="st">&#39;spearman&#39;</span>)</span>
<span id="cb117-2"><a href="introduction-to-species-distribution-modeling.html#cb117-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb117-3"><a href="introduction-to-species-distribution-modeling.html#cb117-3" aria-hidden="true" tabindex="-1"></a><span class="fu">corrplot.mixed</span>(cor_mat, <span class="at">tl.pos=</span><span class="st">&#39;d&#39;</span>, <span class="at">tl.cex=</span><span class="fl">0.6</span>, <span class="at">number.cex=</span><span class="fl">0.5</span>, <span class="at">addCoefasPercent=</span>T)</span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-34-1.png" width="672" /></p>
<p>We can use a function called “select07” to remove highly correlated variables (variables greater than 70% = 0.7). (See Dorman et al 2013)</p>
<div class="sourceCode" id="cb118"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb118-1"><a href="introduction-to-species-distribution-modeling.html#cb118-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(devtools)</span></code></pre></div>
<pre><code>## Loading required package: usethis</code></pre>
<pre><code>## Warning: package &#39;usethis&#39; was built under R version 4.0.5</code></pre>
<div class="sourceCode" id="cb121"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb121-1"><a href="introduction-to-species-distribution-modeling.html#cb121-1" aria-hidden="true" tabindex="-1"></a><span class="co">#devtools::install_git(&quot;https://gitup.uni-potsdam.de/macroecology/mecofun.git&quot;)</span></span>
<span id="cb121-2"><a href="introduction-to-species-distribution-modeling.html#cb121-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb121-3"><a href="introduction-to-species-distribution-modeling.html#cb121-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(mecofun)</span>
<span id="cb121-4"><a href="introduction-to-species-distribution-modeling.html#cb121-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb121-5"><a href="introduction-to-species-distribution-modeling.html#cb121-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Run select07()</span></span>
<span id="cb121-6"><a href="introduction-to-species-distribution-modeling.html#cb121-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb121-7"><a href="introduction-to-species-distribution-modeling.html#cb121-7" aria-hidden="true" tabindex="-1"></a>var_sel <span class="ot">&lt;-</span> <span class="fu">select07</span>(<span class="at">X=</span>Mona_PA[,<span class="sc">-</span><span class="fu">c</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">4</span>)], </span>
<span id="cb121-8"><a href="introduction-to-species-distribution-modeling.html#cb121-8" aria-hidden="true" tabindex="-1"></a>                    <span class="at">y=</span>Mona_PA<span class="sc">$</span>occ, </span>
<span id="cb121-9"><a href="introduction-to-species-distribution-modeling.html#cb121-9" aria-hidden="true" tabindex="-1"></a>                    <span class="at">threshold=</span><span class="fl">0.7</span>)</span></code></pre></div>
<pre><code>## Warning: glm.fit: fitted probabilities numerically 0 or 1 occurred</code></pre>
<pre><code>## Warning: glm.fit: fitted probabilities numerically 0 or 1 occurred

## Warning: glm.fit: fitted probabilities numerically 0 or 1 occurred

## Warning: glm.fit: fitted probabilities numerically 0 or 1 occurred

## Warning: glm.fit: fitted probabilities numerically 0 or 1 occurred

## Warning: glm.fit: fitted probabilities numerically 0 or 1 occurred

## Warning: glm.fit: fitted probabilities numerically 0 or 1 occurred

## Warning: glm.fit: fitted probabilities numerically 0 or 1 occurred

## Warning: glm.fit: fitted probabilities numerically 0 or 1 occurred</code></pre>
<div class="sourceCode" id="cb124"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb124-1"><a href="introduction-to-species-distribution-modeling.html#cb124-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Check out the structure of the resulting object:</span></span>
<span id="cb124-2"><a href="introduction-to-species-distribution-modeling.html#cb124-2" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(var_sel)</span></code></pre></div>
<pre><code>## List of 3
##  $ AIC     : Named num [1:19] 197 197 213 241 257 ...
##   ..- attr(*, &quot;names&quot;)= chr [1:19] &quot;bio4&quot; &quot;bio6&quot; &quot;bio3&quot; &quot;bio7&quot; ...
##  $ cor_mat : num [1:19, 1:19] 1 -0.108 0.365 -0.277 0.494 ...
##   ..- attr(*, &quot;dimnames&quot;)=List of 2
##   .. ..$ : chr [1:19] &quot;bio1&quot; &quot;bio2&quot; &quot;bio3&quot; &quot;bio4&quot; ...
##   .. ..$ : chr [1:19] &quot;bio1&quot; &quot;bio2&quot; &quot;bio3&quot; &quot;bio4&quot; ...
##  $ pred_sel: chr [1:9] &quot;bio4&quot; &quot;bio6&quot; &quot;bio15&quot; &quot;bio19&quot; ...</code></pre>
<div class="sourceCode" id="cb126"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb126-1"><a href="introduction-to-species-distribution-modeling.html#cb126-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Extract the names of the weakly correlated predictors in order of their AIC:</span></span>
<span id="cb126-2"><a href="introduction-to-species-distribution-modeling.html#cb126-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb126-3"><a href="introduction-to-species-distribution-modeling.html#cb126-3" aria-hidden="true" tabindex="-1"></a>pred_sel <span class="ot">=</span> var_sel<span class="sc">$</span>pred_sel</span>
<span id="cb126-4"><a href="introduction-to-species-distribution-modeling.html#cb126-4" aria-hidden="true" tabindex="-1"></a>pred_sel</span></code></pre></div>
<pre><code>## [1] &quot;bio4&quot;  &quot;bio6&quot;  &quot;bio15&quot; &quot;bio19&quot; &quot;bio9&quot;  &quot;bio10&quot; &quot;bio2&quot;  &quot;bio8&quot;  &quot;bio18&quot;</code></pre>
<p>See important variables in that order</p>
</div>
<div id="model-selection" class="section level3" number="6.0.7">
<h3><span class="header-section-number">6.0.7</span> Model selection</h3>
<p>We can fit different regression model to predict our species. This model can take linear function, quadratic or polynomial. We can then use vif or AIC to determine which one work best for this model. For the sake of this exercise, I will only fit Linear relationship.</p>
<div class="sourceCode" id="cb128"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb128-1"><a href="introduction-to-species-distribution-modeling.html#cb128-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Take any bioclim variable and fit a GLM assuming a linear relationship:</span></span>
<span id="cb128-2"><a href="introduction-to-species-distribution-modeling.html#cb128-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb128-3"><a href="introduction-to-species-distribution-modeling.html#cb128-3" aria-hidden="true" tabindex="-1"></a>model_linear <span class="ot">&lt;-</span> <span class="fu">glm</span>(occ <span class="sc">~</span> bio19, <span class="at">family=</span><span class="fu">binomial</span>(<span class="at">link=</span>logit), <span class="at">data=</span> Mona_PA)</span>
<span id="cb128-4"><a href="introduction-to-species-distribution-modeling.html#cb128-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb128-5"><a href="introduction-to-species-distribution-modeling.html#cb128-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_linear) </span></code></pre></div>
<pre><code>## 
## Call:
## glm(formula = occ ~ bio19, family = binomial(link = logit), data = Mona_PA)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -3.0272  -0.7494  -0.6247   1.0343   1.6464  
## 
## Coefficients:
##               Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept) -1.5350688  0.2064067  -7.437 1.03e-13 ***
## bio19        0.0038553  0.0005399   7.141 9.26e-13 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 393.60  on 288  degrees of freedom
## Residual deviance: 310.23  on 287  degrees of freedom
## AIC: 314.23
## 
## Number of Fisher Scoring iterations: 4</code></pre>
<p>Okay, let’s fit a quadratic relationship with the same bioclim var used above:</p>
<div class="sourceCode" id="cb130"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb130-1"><a href="introduction-to-species-distribution-modeling.html#cb130-1" aria-hidden="true" tabindex="-1"></a>model_quad <span class="ot">&lt;-</span> <span class="fu">glm</span>(occ <span class="sc">~</span> bio19 <span class="sc">+</span> <span class="fu">I</span>(bio19<span class="sc">^</span><span class="dv">2</span>), <span class="at">family=</span><span class="fu">binomial</span>(<span class="at">link=</span>logit), <span class="at">data=</span> Mona_PA)</span>
<span id="cb130-2"><a href="introduction-to-species-distribution-modeling.html#cb130-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb130-3"><a href="introduction-to-species-distribution-modeling.html#cb130-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_quad)</span></code></pre></div>
<pre><code>## 
## Call:
## glm(formula = occ ~ bio19 + I(bio19^2), family = binomial(link = logit), 
##     data = Mona_PA)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -2.1023  -0.6376  -0.3866   0.7762   1.7656  
## 
## Coefficients:
##               Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept) -2.557e+00  3.115e-01  -8.207 2.27e-16 ***
## bio19        1.071e-02  1.363e-03   7.860 3.83e-15 ***
## I(bio19^2)  -6.134e-06  1.003e-06  -6.112 9.81e-10 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 393.60  on 288  degrees of freedom
## Residual deviance: 271.78  on 286  degrees of freedom
## AIC: 277.78
## 
## Number of Fisher Scoring iterations: 4</code></pre>
<p>We can now use a Maximum likelihood estimator to select which model is best and fit the SDM. N.B- the lower your AIC, the better. So any model with AIC is the best model to be selected</p>
<div class="sourceCode" id="cb132"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb132-1"><a href="introduction-to-species-distribution-modeling.html#cb132-1" aria-hidden="true" tabindex="-1"></a><span class="fu">AIC</span>(model_linear) </span></code></pre></div>
<pre><code>## [1] 314.2324</code></pre>
<div class="sourceCode" id="cb134"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb134-1"><a href="introduction-to-species-distribution-modeling.html#cb134-1" aria-hidden="true" tabindex="-1"></a><span class="fu">AIC</span>(model_quad)</span></code></pre></div>
<pre><code>## [1] 277.7795</code></pre>
<p>Voila! Ideally, including the interaction term (quadratic function) seems to make more sense for this model. However, as I said earlier, for the sake of this exercise, I will just continue with linear model to demonstrate what we really want to know. If you want to do more (include quadratic or anything), you can go ahead using the same model formula above or reach out to me if you have issues or concerns.</p>
</div>
<div id="fitting-the-model" class="section level3" number="6.0.8">
<h3><span class="header-section-number">6.0.8</span> Fitting the model</h3>
<p>Now that we know which model to fit, we can select the model and then evaluate the prediction.</p>
<div class="sourceCode" id="cb136"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb136-1"><a href="introduction-to-species-distribution-modeling.html#cb136-1" aria-hidden="true" tabindex="-1"></a><span class="co"># regression model</span></span>
<span id="cb136-2"><a href="introduction-to-species-distribution-modeling.html#cb136-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb136-3"><a href="introduction-to-species-distribution-modeling.html#cb136-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb136-4"><a href="introduction-to-species-distribution-modeling.html#cb136-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb136-5"><a href="introduction-to-species-distribution-modeling.html#cb136-5" aria-hidden="true" tabindex="-1"></a>model <span class="ot">=</span> <span class="fu">step</span>(<span class="fu">glm</span>(occ <span class="sc">~</span> bio4 <span class="sc">+</span> bio6 <span class="sc">+</span> bio15 <span class="sc">+</span> bio19, <span class="at">family=</span><span class="fu">binomial</span>(<span class="at">link=</span>logit), <span class="at">data=</span> Mona_PA))</span></code></pre></div>
<pre><code>## Start:  AIC=183.44
## occ ~ bio4 + bio6 + bio15 + bio19</code></pre>
<pre><code>## Warning: glm.fit: fitted probabilities numerically 0 or 1 occurred</code></pre>
<pre><code>##         Df Deviance    AIC
## - bio15  1   173.53 181.53
## &lt;none&gt;       173.44 183.44
## - bio4   1   179.20 187.20
## - bio19  1   187.58 195.58
## - bio6   1   263.93 271.93
## 
## Step:  AIC=181.53
## occ ~ bio4 + bio6 + bio19
## 
##         Df Deviance    AIC
## &lt;none&gt;       173.53 181.53
## - bio4   1   181.99 187.99
## - bio19  1   187.62 193.62
## - bio6   1   265.54 271.54</code></pre>
<div class="sourceCode" id="cb140"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb140-1"><a href="introduction-to-species-distribution-modeling.html#cb140-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model)</span></code></pre></div>
<pre><code>## 
## Call:
## glm(formula = occ ~ bio4 + bio6 + bio19, family = binomial(link = logit), 
##     data = Mona_PA)
## 
## Deviance Residuals: 
##      Min        1Q    Median        3Q       Max  
## -3.10852  -0.30152  -0.00401   0.49153   1.94663  
## 
## Coefficients:
##               Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept) -1.584e+01  2.342e+00  -6.762 1.36e-11 ***
## bio4         8.983e-04  2.862e-04   3.139 0.001697 ** 
## bio6         7.347e-02  1.034e-02   7.105 1.20e-12 ***
## bio19        2.205e-03  6.460e-04   3.413 0.000642 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 393.60  on 288  degrees of freedom
## Residual deviance: 173.53  on 285  degrees of freedom
## AIC: 181.53
## 
## Number of Fisher Scoring iterations: 7</code></pre>
<div class="sourceCode" id="cb142"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb142-1"><a href="introduction-to-species-distribution-modeling.html#cb142-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Let&#39;s see the plot of Occurrence</span></span>
<span id="cb142-2"><a href="introduction-to-species-distribution-modeling.html#cb142-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb142-3"><a href="introduction-to-species-distribution-modeling.html#cb142-3" aria-hidden="true" tabindex="-1"></a>my_preds <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&#39;bio4&#39;</span>, <span class="st">&#39;bio6&#39;</span>, <span class="st">&quot;bio15&quot;</span>, <span class="st">&quot;bio19&quot;</span>)</span>
<span id="cb142-4"><a href="introduction-to-species-distribution-modeling.html#cb142-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb142-5"><a href="introduction-to-species-distribution-modeling.html#cb142-5" aria-hidden="true" tabindex="-1"></a>bio_clim_df1 <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="fu">rasterToPoints</span>(clim_data[[my_preds]]))</span>
<span id="cb142-6"><a href="introduction-to-species-distribution-modeling.html#cb142-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb142-7"><a href="introduction-to-species-distribution-modeling.html#cb142-7" aria-hidden="true" tabindex="-1"></a><span class="fu">any</span>(<span class="fu">is.na</span>(bio_clim_df1))</span></code></pre></div>
<pre><code>## [1] TRUE</code></pre>
<div class="sourceCode" id="cb144"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb144-1"><a href="introduction-to-species-distribution-modeling.html#cb144-1" aria-hidden="true" tabindex="-1"></a>bio_clim_df1<span class="ot">&lt;-</span> <span class="fu">na.omit</span>(bio_clim_df1)</span>
<span id="cb144-2"><a href="introduction-to-species-distribution-modeling.html#cb144-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb144-3"><a href="introduction-to-species-distribution-modeling.html#cb144-3" aria-hidden="true" tabindex="-1"></a>Model_glm_pred <span class="ot">&lt;-</span> <span class="fu">rasterFromXYZ</span>(<span class="fu">cbind</span>(bio_clim_df1[,<span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>],<span class="fu">predict</span>(model, bio_clim_df1, <span class="at">type=</span><span class="st">&#39;response&#39;</span>)))</span>
<span id="cb144-4"><a href="introduction-to-species-distribution-modeling.html#cb144-4" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>((Model_glm_pred),</span>
<span id="cb144-5"><a href="introduction-to-species-distribution-modeling.html#cb144-5" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlim =</span> <span class="fu">c</span>(<span class="fu">min</span>(Mona_PA<span class="sc">$</span>decimalLongitude),<span class="fu">max</span> (Mona_PA<span class="sc">$</span>decimalLongitude)),</span>
<span id="cb144-6"><a href="introduction-to-species-distribution-modeling.html#cb144-6" aria-hidden="true" tabindex="-1"></a>     <span class="at">ylim =</span> <span class="fu">c</span>(<span class="fu">min</span>(Mona_PA<span class="sc">$</span>decimalLatitude), <span class="fu">max</span>(Mona_PA<span class="sc">$</span>decimalLatitude)),</span>
<span id="cb144-7"><a href="introduction-to-species-distribution-modeling.html#cb144-7" aria-hidden="true" tabindex="-1"></a>     <span class="at">main=</span><span class="st">&#39;Probability of Occurence&#39;</span>, <span class="at">axes=</span>F)  </span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-40-1.png" width="672" /></p>
<p>Good. You can see the habitat suitability right? or the probability of occurrence for Mona Monkey. How about we zoom in to Africa and check it well?</p>
<p>Run the code below to zoom into Africa</p>
<div class="sourceCode" id="cb145"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb145-1"><a href="introduction-to-species-distribution-modeling.html#cb145-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>((Model_glm_pred),</span>
<span id="cb145-2"><a href="introduction-to-species-distribution-modeling.html#cb145-2" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlim =</span> <span class="fu">c</span>(<span class="fu">min</span>(<span class="sc">-</span><span class="dv">25</span>),<span class="fu">max</span> (<span class="dv">50</span>)),</span>
<span id="cb145-3"><a href="introduction-to-species-distribution-modeling.html#cb145-3" aria-hidden="true" tabindex="-1"></a>     <span class="at">ylim =</span> <span class="fu">c</span>(<span class="fu">min</span>(<span class="sc">-</span><span class="dv">40</span>), <span class="fu">max</span>(<span class="dv">40</span>)),</span>
<span id="cb145-4"><a href="introduction-to-species-distribution-modeling.html#cb145-4" aria-hidden="true" tabindex="-1"></a>     <span class="at">main=</span><span class="st">&#39;Probability of Occurence- Mona Monkey&#39;</span>, <span class="at">axes=</span>F)  </span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-41-1.png" width="672" /></p>
<p>You may want to assess the goodness of fit</p>
<div class="sourceCode" id="cb146"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb146-1"><a href="introduction-to-species-distribution-modeling.html#cb146-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Explained deviance:</span></span>
<span id="cb146-2"><a href="introduction-to-species-distribution-modeling.html#cb146-2" aria-hidden="true" tabindex="-1"></a><span class="fu">expl_deviance</span>(<span class="at">obs =</span> Mona_PA<span class="sc">$</span>occ,</span>
<span id="cb146-3"><a href="introduction-to-species-distribution-modeling.html#cb146-3" aria-hidden="true" tabindex="-1"></a>              <span class="at">pred =</span> model<span class="sc">$</span>fitted)</span></code></pre></div>
<pre><code>## [1] 0.5591346</code></pre>
<p>55.9% of the predictors explained the deviance in the model</p>
<p>Okay, that’s not what we want to do with SDM here. Let’s transfer the probability of occurence to binary prediction</p>
</div>
<div id="model-evaluation-and-validation" class="section level3" number="6.0.9">
<h3><span class="header-section-number">6.0.9</span> Model evaluation and validation</h3>
<p>Because we need to evaluate the prediction (of course if you write exam, you want to know how well you perform), so we need to set up evaluation dataset. The approach to do this (as in remote sensing) is to divide (randomly) the data into testing and training. So, let’s set out 70% of our Mona monkey as training data and the remaining 30% for testing later. Lastly, we have selected linear function up there, so we are good to go and can fit different algorithms now.</p>
<p>Split and train the model</p>
<div class="sourceCode" id="cb148"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb148-1"><a href="introduction-to-species-distribution-modeling.html#cb148-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Use 70% for training data (of course you can change it and use 60 or 80% depending on you)</span></span>
<span id="cb148-2"><a href="introduction-to-species-distribution-modeling.html#cb148-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb148-3"><a href="introduction-to-species-distribution-modeling.html#cb148-3" aria-hidden="true" tabindex="-1"></a>train_data <span class="ot">&lt;-</span> <span class="fu">sample</span>(<span class="fu">seq_len</span>(<span class="fu">nrow</span>(Mona_PA)), <span class="at">size=</span><span class="fu">round</span>(<span class="fl">0.7</span><span class="sc">*</span><span class="fu">nrow</span>(Mona_PA)))</span>
<span id="cb148-4"><a href="introduction-to-species-distribution-modeling.html#cb148-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb148-5"><a href="introduction-to-species-distribution-modeling.html#cb148-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Okay, let&#39;s subset the training &amp; testing data</span></span>
<span id="cb148-6"><a href="introduction-to-species-distribution-modeling.html#cb148-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb148-7"><a href="introduction-to-species-distribution-modeling.html#cb148-7" aria-hidden="true" tabindex="-1"></a>Mona_train <span class="ot">&lt;-</span> Mona_PA[train_data,]</span>
<span id="cb148-8"><a href="introduction-to-species-distribution-modeling.html#cb148-8" aria-hidden="true" tabindex="-1"></a>Mona_test <span class="ot">&lt;-</span> Mona_PA[<span class="sc">-</span>train_data,]</span>
<span id="cb148-9"><a href="introduction-to-species-distribution-modeling.html#cb148-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb148-10"><a href="introduction-to-species-distribution-modeling.html#cb148-10" aria-hidden="true" tabindex="-1"></a><span class="co"># If you want to store the split information for later use, use this code: </span></span>
<span id="cb148-11"><a href="introduction-to-species-distribution-modeling.html#cb148-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb148-12"><a href="introduction-to-species-distribution-modeling.html#cb148-12" aria-hidden="true" tabindex="-1"></a><span class="co">#write(train_data, file = &quot;Mona_traindata.txt&quot;)</span></span>
<span id="cb148-13"><a href="introduction-to-species-distribution-modeling.html#cb148-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb148-14"><a href="introduction-to-species-distribution-modeling.html#cb148-14" aria-hidden="true" tabindex="-1"></a><span class="co">#remember I said we can store other file than csv alone right?)</span></span></code></pre></div>
<p>Using our GLM regression (but now on the training data) to evaluate how well it perform</p>
<div class="sourceCode" id="cb149"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb149-1"><a href="introduction-to-species-distribution-modeling.html#cb149-1" aria-hidden="true" tabindex="-1"></a>model_glm <span class="ot">=</span> <span class="fu">step</span>(<span class="fu">glm</span>(occ <span class="sc">~</span> bio4 <span class="sc">+</span> bio6 <span class="sc">+</span> bio15 <span class="sc">+</span> bio19, <span class="at">family=</span><span class="fu">binomial</span>(<span class="at">link=</span>logit), <span class="at">data=</span> Mona_train))</span></code></pre></div>
<pre><code>## Start:  AIC=133.16
## occ ~ bio4 + bio6 + bio15 + bio19
## 
##         Df Deviance    AIC
## - bio15  1   123.17 131.17
## &lt;none&gt;       123.16 133.16
## - bio4   1   128.90 136.90
## - bio19  1   130.47 138.47
## - bio6   1   184.25 192.25
## 
## Step:  AIC=131.17
## occ ~ bio4 + bio6 + bio19
## 
##         Df Deviance    AIC
## &lt;none&gt;       123.17 131.17
## - bio4   1   129.74 135.74
## - bio19  1   130.60 136.60
## - bio6   1   185.95 191.95</code></pre>
<div class="sourceCode" id="cb151"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb151-1"><a href="introduction-to-species-distribution-modeling.html#cb151-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_glm)</span></code></pre></div>
<pre><code>## 
## Call:
## glm(formula = occ ~ bio4 + bio6 + bio19, family = binomial(link = logit), 
##     data = Mona_train)
## 
## Deviance Residuals: 
##      Min        1Q    Median        3Q       Max  
## -2.95547  -0.29929  -0.00348   0.48366   2.02285  
## 
## Coefficients:
##               Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept) -1.574e+01  2.877e+00  -5.471 4.49e-08 ***
## bio4         9.193e-04  3.352e-04   2.742   0.0061 ** 
## bio6         7.370e-02  1.284e-02   5.740 9.48e-09 ***
## bio19        1.799e-03  7.148e-04   2.517   0.0118 *  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 277.17  on 201  degrees of freedom
## Residual deviance: 123.17  on 198  degrees of freedom
## AIC: 131.17
## 
## Number of Fisher Scoring iterations: 7</code></pre>
<p>You may want to check the response curve</p>
<div class="sourceCode" id="cb153"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb153-1"><a href="introduction-to-species-distribution-modeling.html#cb153-1" aria-hidden="true" tabindex="-1"></a>my_preds <span class="ot">=</span> <span class="fu">c</span>(<span class="st">&quot;bio4&quot;</span>, <span class="st">&quot;bio6&quot;</span>, <span class="st">&quot;bio15&quot;</span>, <span class="st">&quot;bio19&quot;</span>)</span>
<span id="cb153-2"><a href="introduction-to-species-distribution-modeling.html#cb153-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb153-3"><a href="introduction-to-species-distribution-modeling.html#cb153-3" aria-hidden="true" tabindex="-1"></a>preds_cv <span class="ot">&lt;-</span> <span class="fu">crossvalSDM</span>(model_glm, <span class="at">traindat =</span> Mona_train, <span class="at">colname_species =</span> <span class="st">&#39;occ&#39;</span>, <span class="at">colname_pred =</span> my_preds)</span>
<span id="cb153-4"><a href="introduction-to-species-distribution-modeling.html#cb153-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb153-5"><a href="introduction-to-species-distribution-modeling.html#cb153-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb153-6"><a href="introduction-to-species-distribution-modeling.html#cb153-6" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(model_glm<span class="sc">$</span>fitted.values, preds_cv, <span class="at">xlab=</span><span class="st">&#39;Fitted values&#39;</span>, <span class="at">ylab=</span><span class="st">&#39;Predicted values from CV&#39;</span>)</span>
<span id="cb153-7"><a href="introduction-to-species-distribution-modeling.html#cb153-7" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="dv">0</span>,<span class="dv">1</span>,<span class="at">col=</span><span class="st">&#39;red&#39;</span>,<span class="at">lwd=</span><span class="dv">2</span>)</span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-45-1.png" width="672" /></p>
<p>Before we map the prediction, let’s threshold the data (and try check the threshold independent metrics- AUC)</p>
<p>Thresholding</p>
<div class="sourceCode" id="cb154"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb154-1"><a href="introduction-to-species-distribution-modeling.html#cb154-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(PresenceAbsence)</span>
<span id="cb154-2"><a href="introduction-to-species-distribution-modeling.html#cb154-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb154-3"><a href="introduction-to-species-distribution-modeling.html#cb154-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb154-4"><a href="introduction-to-species-distribution-modeling.html#cb154-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Cross-validated predictions:</span></span>
<span id="cb154-5"><a href="introduction-to-species-distribution-modeling.html#cb154-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb154-6"><a href="introduction-to-species-distribution-modeling.html#cb154-6" aria-hidden="true" tabindex="-1"></a>threshold_data <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">ID =</span> <span class="fu">seq_len</span>(<span class="fu">nrow</span>(Mona_train)), <span class="at">obs =</span> Mona_train<span class="sc">$</span>occ, <span class="at">pred =</span> preds_cv)</span>
<span id="cb154-7"><a href="introduction-to-species-distribution-modeling.html#cb154-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb154-8"><a href="introduction-to-species-distribution-modeling.html#cb154-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Get the optimal thresholds:     </span></span>
<span id="cb154-9"><a href="introduction-to-species-distribution-modeling.html#cb154-9" aria-hidden="true" tabindex="-1"></a>(threshold_optimal <span class="ot">&lt;-</span> PresenceAbsence<span class="sc">::</span><span class="fu">optimal.thresholds</span>(<span class="at">DATA=</span> threshold_data))</span></code></pre></div>
<pre><code>## Warning in PresenceAbsence::optimal.thresholds(DATA = threshold_data): req.sens defaults to 0.85</code></pre>
<pre><code>## Warning in PresenceAbsence::optimal.thresholds(DATA = threshold_data): req.spec defaults to 0.85</code></pre>
<pre><code>## Warning in PresenceAbsence::optimal.thresholds(DATA = threshold_data): costs assumed to be equal</code></pre>
<pre><code>##          Method      pred
## 1       Default 0.5000000
## 2     Sens=Spec 0.4850000
## 3  MaxSens+Spec 0.3700000
## 4      MaxKappa 0.3700000
## 5        MaxPCC 0.3700000
## 6  PredPrev=Obs 0.5350000
## 7       ObsPrev 0.4405941
## 8      MeanProb 0.4402461
## 9    MinROCdist 0.3700000
## 10      ReqSens 0.5000000
## 11      ReqSpec 0.4800000
## 12         Cost 0.3700000</code></pre>
<p>Good. You can now use any values above to threshold your species data to “presence” and “absence”</p>
<div class="sourceCode" id="cb159"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb159-1"><a href="introduction-to-species-distribution-modeling.html#cb159-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Threshold using the max sen+spec</span></span>
<span id="cb159-2"><a href="introduction-to-species-distribution-modeling.html#cb159-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb159-3"><a href="introduction-to-species-distribution-modeling.html#cb159-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Print the confusion Matrix</span></span>
<span id="cb159-4"><a href="introduction-to-species-distribution-modeling.html#cb159-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb159-5"><a href="introduction-to-species-distribution-modeling.html#cb159-5" aria-hidden="true" tabindex="-1"></a>(cmx_maxSSS <span class="ot">&lt;-</span> PresenceAbsence<span class="sc">::</span><span class="fu">cmx</span>(<span class="at">DATA=</span> threshold_data, <span class="at">threshold=</span>threshold_optimal[<span class="dv">3</span>,<span class="dv">2</span>]))</span></code></pre></div>
<pre><code>##          observed
## predicted  1  0
##         1 85 18
##         0  4 95</code></pre>
<p>Let’s compute AUC</p>
<div class="sourceCode" id="cb161"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb161-1"><a href="introduction-to-species-distribution-modeling.html#cb161-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(AUC)</span></code></pre></div>
<pre><code>## AUC 0.3.0</code></pre>
<pre><code>## Type AUCNews() to see the change log and ?AUC to get an overview.</code></pre>
<pre><code>## 
## Attaching package: &#39;AUC&#39;</code></pre>
<pre><code>## The following objects are masked from &#39;package:PresenceAbsence&#39;:
## 
##     auc, sensitivity, specificity</code></pre>
<div class="sourceCode" id="cb166"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb166-1"><a href="introduction-to-species-distribution-modeling.html#cb166-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Let&#39;s have a look a the ROC curve:</span></span>
<span id="cb166-2"><a href="introduction-to-species-distribution-modeling.html#cb166-2" aria-hidden="true" tabindex="-1"></a>roc_cv <span class="ot">&lt;-</span> <span class="fu">roc</span>(preds_cv, <span class="fu">as.factor</span>(Mona_train<span class="sc">$</span>occ))</span>
<span id="cb166-3"><a href="introduction-to-species-distribution-modeling.html#cb166-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(roc_cv, <span class="at">col =</span> <span class="st">&quot;grey70&quot;</span>, <span class="at">lwd =</span> <span class="dv">2</span>)</span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-48-1.png" width="672" /></p>
<p>Compute the AUC and other evaluation metrics:</p>
<div class="sourceCode" id="cb167"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb167-1"><a href="introduction-to-species-distribution-modeling.html#cb167-1" aria-hidden="true" tabindex="-1"></a>(<span class="at">evaluation_metrics =</span> <span class="fu">evalSDM</span>(Mona_train<span class="sc">$</span>occ, preds_cv, <span class="at">thresh.method =</span> <span class="st">&quot;MaxSens+Spec&quot;</span>))</span></code></pre></div>
<pre><code>##         AUC       TSS     Kappa      Sens     Spec       PCC        D2 thresh
## 1 0.9281098 0.7957641 0.7826895 0.9550562 0.840708 0.8910891 0.5246774   0.37</code></pre>
<p>We can now validate the model performance on the test data</p>
<div class="sourceCode" id="cb169"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb169-1"><a href="introduction-to-species-distribution-modeling.html#cb169-1" aria-hidden="true" tabindex="-1"></a>(performance_glm <span class="ot">&lt;-</span> <span class="fu">evalSDM</span>(Mona_test<span class="sc">$</span>occ, <span class="fu">predict</span>(model_glm, Mona_test[,my_preds], <span class="at">type=</span><span class="st">&#39;response&#39;</span>), <span class="at">thresh.method =</span>  <span class="st">&quot;MaxSens+Spec&quot;</span>))</span></code></pre></div>
<pre><code>##         AUC       TSS     Kappa      Sens      Spec       PCC        D2 thresh
## 1 0.9393939 0.7441077 0.7529813 0.8181818 0.9259259 0.8850575 0.5591624   0.49</code></pre>
<p>Please note-</p>
<p>Sensitivity = true positive rate
Specificity = true negative rate
PCC = Proportion of correctly classified observations,</p>
<p>We can evaluate if the model is good or not with TSS (true skill statistics or Kappa). You can also chekc AUC (Area under the curve). You may ask which curve, the ROC curve- Receiver operating characteristics.</p>
</div>
<div id="map-prediction" class="section level3" number="6.0.10">
<h3><span class="header-section-number">6.0.10</span> Map prediction</h3>
<p>Now, let’s check the Map prediction by plotting the main binary map with the data-</p>
<div class="sourceCode" id="cb171"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb171-1"><a href="introduction-to-species-distribution-modeling.html#cb171-1" aria-hidden="true" tabindex="-1"></a>bio_clim_df_2 <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="fu">rasterToPoints</span>(clim_data[[my_preds]]))</span>
<span id="cb171-2"><a href="introduction-to-species-distribution-modeling.html#cb171-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb171-3"><a href="introduction-to-species-distribution-modeling.html#cb171-3" aria-hidden="true" tabindex="-1"></a><span class="fu">any</span>(<span class="fu">is.na</span>(bio_clim_df_2))</span></code></pre></div>
<pre><code>## [1] TRUE</code></pre>
<div class="sourceCode" id="cb173"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb173-1"><a href="introduction-to-species-distribution-modeling.html#cb173-1" aria-hidden="true" tabindex="-1"></a>bio_clim_df_2<span class="ot">&lt;-</span> <span class="fu">na.omit</span>(bio_clim_df_2)</span>
<span id="cb173-2"><a href="introduction-to-species-distribution-modeling.html#cb173-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb173-3"><a href="introduction-to-species-distribution-modeling.html#cb173-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb173-4"><a href="introduction-to-species-distribution-modeling.html#cb173-4" aria-hidden="true" tabindex="-1"></a>binary_glm <span class="ot">&lt;-</span> predicted_glm <span class="ot">&lt;-</span> <span class="fu">rasterFromXYZ</span>(<span class="fu">cbind</span>(bio_clim_df_2[,<span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>],<span class="fu">predict</span>(model_glm, bio_clim_df_2, <span class="at">type=</span><span class="st">&#39;response&#39;</span>)))</span>
<span id="cb173-5"><a href="introduction-to-species-distribution-modeling.html#cb173-5" aria-hidden="true" tabindex="-1"></a><span class="fu">values</span>(binary_glm) <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(<span class="fu">values</span>(predicted_glm)<span class="sc">&gt;=</span> performance_glm<span class="sc">$</span>thresh, <span class="dv">1</span>, <span class="dv">0</span>)</span>
<span id="cb173-6"><a href="introduction-to-species-distribution-modeling.html#cb173-6" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">stack</span>(predicted_glm, binary_glm),</span>
<span id="cb173-7"><a href="introduction-to-species-distribution-modeling.html#cb173-7" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlim =</span> <span class="fu">c</span>(<span class="fu">min</span>(<span class="sc">-</span><span class="dv">25</span>),<span class="fu">max</span> (<span class="dv">50</span>)),</span>
<span id="cb173-8"><a href="introduction-to-species-distribution-modeling.html#cb173-8" aria-hidden="true" tabindex="-1"></a>     <span class="at">ylim =</span> <span class="fu">c</span>(<span class="fu">min</span>(<span class="sc">-</span><span class="dv">40</span>), <span class="fu">max</span>(<span class="dv">40</span>)),</span>
<span id="cb173-9"><a href="introduction-to-species-distribution-modeling.html#cb173-9" aria-hidden="true" tabindex="-1"></a>     <span class="at">main=</span><span class="fu">c</span>(<span class="st">&#39;Probability of Occurrence-Mona&#39;</span>,<span class="st">&#39;Binary Prediction-Mona&#39;</span>), <span class="at">axes=</span>F)  </span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-51-1.png" width="672" /></p>
<p>Now, you can see the binary prediction of Mona Monkey throughout Africa.</p>
<p>Great! We stopped here in class. I will update the book later as time permits (check back soon):</p>
<ol style="list-style-type: decimal">
<li>Transfer this prediction to future (2050 or 2070)</li>
<li>Use different model algorithms (random forest, boosted regression trees, etc)</li>
<li>Ensemble the models (to account for model uncertainty) and lots more.</li>
</ol>
<p>If you have questions, feel free to ask email me or slack me.</p>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="basic-statistical-analysis.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="resources-and-references.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/drhammed/bookdown_workshop/edit/master/Chapter-6.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": "https://github.com/drhammed/bookdown_workshop/blob/master/Chapter-6.Rmd",
"text": null
},
"download": null,
"toc": {
"collapse": "subsection"
}
});
});
</script>

</body>

</html>
